name: Build and Assert Assets Exists
description: Build the package and assert that file contents exist as we expect
runs:
  using: "composite"
  steps:
    - name: Build and Assert Output
      shell: bash
      run: pnpm build
      working-directory: package
    - name: Upload dist assets to cache
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: ${{ env.dist }}
