name: Setup node and pnpm
description: Setup node and install dependencies using pnpm
runs:
  using: "composite"
  steps:
    - name: Install Nodes.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install pnpm
      uses: pnpm/action-setup@v2.4.0
      with:
        version: 7.3.0
        run_install: false
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    - name: Install dependencies
      shell: bash
      run: pnpm install
    # - name: "Install dependencies"
    #   shell: "bash"
    #   run: |
    #     pnpm -v
    #     pnpm install --fix-lockfile
    #     git_diff=$(git diff)
    #     if [[ "$git_diff" -eq "" ]]; then
    #       echo "Success: no lockfile differences" ;
    #     else
    #       echo "Error: lockfile differences detected";
    #     fi
