name: Install lint and test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CI: true
  dist: package/dist

jobs:
  install_dependencies:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm
  build:
    name: Build Tests
    needs: [install_dependencies]
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm
      - uses: ./.github/actions/assert-build
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs:
      - install_dependencies
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm
      - name: Lint
        run: pnpm lint
  typecheck:
    name: "${{ matrix.typescript-scenario }}"
    runs-on: ubuntu-latest
    timeout-minutes: 3
    needs:
      - install_dependencies
    continue-on-error: true
    strategy:
      fail-fast: true
      matrix:
        typescript-scenario:
          - typescript@4.8
          - typescript@4.9
          - typescript@5.0
          - typescript@5.1
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm
      - name: "Change TS to ${{ matrix.typescript-scenario }}"
        run: "pnpm add --save-dev ${{ matrix.typescript-scenario}}"
        working-directory: ./test-app
      - name: "Type checking"
        run: pnpm typecheck
  tests:
    name: Default Tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm
      - uses: ./.github/actions/download-built-package
      - run: pnpm test
  publishDocs:
    name: Publish Demos to Cloudflare Pages
    runs-on: ubuntu-latest
    needs:
      - install_dependencies
    permissions:
      contents: read
      deployments: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: ./.github/actions/pnpm
      - run: pnpm build:docs
      - name: Publish to Cloudflare Pages
        id: publishStep
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.UX_OSS_CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.UX_OSS_CLOUDFLARE_ACCOUNT_ID }}
          projectName: graphics-core
          directory: ./test-app/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |+
            ## Preview URLs
            Env: ${{ steps.publishStep.outputs.environment }}
            Docs: ${{ steps.publishStep.outputs.url }}
  release:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' }}
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: ./.github/actions/pnpm
      - uses: ./.github/actions/download-built-package
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm release
          title: "Release Preview"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
